//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_BUENISIMOEntities : DbContext
    {
        public DB_BUENISIMOEntities()
            : base("name=DB_BUENISIMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAgregados> tbAgregados { get; set; }
        public virtual DbSet<tbAsistencias> tbAsistencias { get; set; }
        public virtual DbSet<tbCategorias> tbCategorias { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbDesechosInsumos> tbDesechosInsumos { get; set; }
        public virtual DbSet<tbDetallePedido> tbDetallePedido { get; set; }
        public virtual DbSet<tbDetalleVenta> tbDetalleVenta { get; set; }
        public virtual DbSet<tbEstadosPedidos> tbEstadosPedidos { get; set; }
        public virtual DbSet<tbHorarios> tbHorarios { get; set; }
        public virtual DbSet<tbIngresosInsumos> tbIngresosInsumos { get; set; }
        public virtual DbSet<tbInsumos> tbInsumos { get; set; }
        public virtual DbSet<tbMedidas> tbMedidas { get; set; }
        public virtual DbSet<tbMesas> tbMesas { get; set; }
        public virtual DbSet<tbMetodosPago> tbMetodosPago { get; set; }
        public virtual DbSet<tbObservacionesAsistencias> tbObservacionesAsistencias { get; set; }
        public virtual DbSet<tbPedidos> tbPedidos { get; set; }
        public virtual DbSet<tbPrecios> tbPrecios { get; set; }
        public virtual DbSet<tbProductos> tbProductos { get; set; }
        public virtual DbSet<tbProveedores> tbProveedores { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbSucursales> tbSucursales { get; set; }
        public virtual DbSet<tbTiposMedidas> tbTiposMedidas { get; set; }
        public virtual DbSet<tbTiposProductos> tbTiposProductos { get; set; }
        public virtual DbSet<tbUnidades> tbUnidades { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbVentas> tbVentas { get; set; }
    
        public virtual int sp_CulminarPedidoYGenerarVenta(Nullable<int> idPedidoACulminar, Nullable<int> idMetodoPago)
        {
            var idPedidoACulminarParameter = idPedidoACulminar.HasValue ?
                new ObjectParameter("idPedidoACulminar", idPedidoACulminar) :
                new ObjectParameter("idPedidoACulminar", typeof(int));
    
            var idMetodoPagoParameter = idMetodoPago.HasValue ?
                new ObjectParameter("idMetodoPago", idMetodoPago) :
                new ObjectParameter("idMetodoPago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CulminarPedidoYGenerarVenta", idPedidoACulminarParameter, idMetodoPagoParameter);
        }
    }
}
