//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleVenta
    {
        public int idDetalleVenta { get; set; }
        public int idVenta { get; set; }
        public Nullable<int> idProductoOriginal { get; set; }
        public string descripcionProducto { get; set; }
        public int cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public string descripcionAgregados { get; set; }
        public decimal precioTotalAgregados { get; set; }
        public string tipoLeche { get; set; }
        public string tipoAzucar { get; set; }
        public string cantidadHielo { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual tbVentas tbVentas { get; set; }
    }
}
