//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIngresosInsumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbIngresosInsumos()
        {
            this.tbDesechosInsumos = new HashSet<tbDesechosInsumos>();
        }
    
        public int idIngresoInsumo { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public int idInsumo { get; set; }
        public decimal cantidad { get; set; }
        public int idUnidad { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string lote { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDesechosInsumos> tbDesechosInsumos { get; set; }
        public virtual tbInsumos tbInsumos { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        public virtual tbSucursales tbSucursales { get; set; }
        public virtual tbUnidades tbUnidades { get; set; }
    }
}
