//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPedidos()
        {
            this.tbDetallePedido = new HashSet<tbDetallePedido>();
        }
    
        public int idPedido { get; set; }
        public string codMesa { get; set; }
        public Nullable<System.DateTime> fechaPedido { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> idEstadoPedido { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetallePedido> tbDetallePedido { get; set; }
        public virtual tbEstadosPedidos tbEstadosPedidos { get; set; }
        public virtual tbMesas tbMesas { get; set; }
        public virtual tbSucursales tbSucursales { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
