//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProveedores()
        {
            this.tbIngresosInsumos = new HashSet<tbIngresosInsumos>();
        }
    
        public int idProveedor { get; set; }
        public string nombreEmpresa { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIngresosInsumos> tbIngresosInsumos { get; set; }
    }
}
