//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBuenisimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVentas()
        {
            this.tbDetalleVenta = new HashSet<tbDetalleVenta>();
        }
    
        public int idVenta { get; set; }
        public Nullable<int> idPedidoOriginal { get; set; }
        public string codMesa { get; set; }
        public int idSucursal { get; set; }
        public int idUsuarioVenta { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public decimal total { get; set; }
        public Nullable<int> idMetodoPago { get; set; }
        public bool fueModificada { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> idUsuarioModificacion { get; set; }
        public string motivoModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleVenta> tbDetalleVenta { get; set; }
        public virtual tbMetodosPago tbMetodosPago { get; set; }
        public virtual tbPedidos tbPedidos { get; set; }
        public virtual tbSucursales tbSucursales { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
