//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAsistencias
    {
        public int idAsistencia { get; set; }
        public int idUsuario { get; set; }
        public int idSucursal { get; set; }
        public int idObservacionAsistencia { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> horaEntrada { get; set; }
        public Nullable<System.DateTime> horaSalida { get; set; }
        public Nullable<int> minutosTardanza { get; set; }
        public Nullable<int> idHorarioAplicado { get; set; }
        public string comentariosAdicionales { get; set; }
    
        public virtual tbHorarios tbHorarios { get; set; }
        public virtual tbObservacionesAsistencias tbObservacionesAsistencias { get; set; }
        public virtual tbSucursales tbSucursales { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
