//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDesechosInsumos
    {
        public int idDesechoInsumo { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public int idInsumo { get; set; }
        public decimal cantidad { get; set; }
        public int idUnidad { get; set; }
        public System.DateTime fechaDesecho { get; set; }
        public string motivo { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idIngresoInsumo { get; set; }
    
        public virtual tbIngresosInsumos tbIngresosInsumos { get; set; }
        public virtual tbInsumos tbInsumos { get; set; }
        public virtual tbSucursales tbSucursales { get; set; }
        public virtual tbUnidades tbUnidades { get; set; }
    }
}
