//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetallePedido
    {
        public int idDetalle { get; set; }
        public Nullable<int> idPedido { get; set; }
        public Nullable<int> idPrecio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual tbPedidos tbPedidos { get; set; }
        public virtual tbPrecios tbPrecios { get; set; }
    }
}
