//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHorarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHorarios()
        {
            this.tbAsistencias = new HashSet<tbAsistencias>();
        }
    
        public int idHorario { get; set; }
        public int idUsuario { get; set; }
        public byte diaSemana { get; set; }
        public System.TimeSpan horaEntrada { get; set; }
        public System.TimeSpan horaSalida { get; set; }
        public decimal pagoPorHora { get; set; }
        public System.DateTime fechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> fechaFinVigencia { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAsistencias> tbAsistencias { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
