//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHorarios
    {
        public int idHorario { get; set; }
        public int idUsuario { get; set; }
        public byte diaSemana { get; set; }
        public System.TimeSpan horaEntradaEsperada { get; set; }
        public System.TimeSpan horaSalidaEsperada { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
