//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrecios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPrecios()
        {
            this.tbDetallePedido = new HashSet<tbDetallePedido>();
        }
    
        public int IdPrecio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdMedida { get; set; }
        public decimal Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetallePedido> tbDetallePedido { get; set; }
        public virtual tbMedidas tbMedidas { get; set; }
        public virtual tbProductos tbProductos { get; set; }
    }
}
