//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWebEficienciaOperativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUnidades()
        {
            this.tbDesechosInsumos = new HashSet<tbDesechosInsumos>();
            this.tbIngresosInsumos = new HashSet<tbIngresosInsumos>();
            this.tbInsumos = new HashSet<tbInsumos>();
        }
    
        public int idUnidad { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string abreviatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDesechosInsumos> tbDesechosInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIngresosInsumos> tbIngresosInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInsumos> tbInsumos { get; set; }
    }
}
